AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'db/*'
    - 'config/*/**'
  TargetRubyVersion: 3.0.1

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes
  
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 160
  
Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 30
  
Style/ClassAndModuleChildren:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false
